version: '3.2'
services:
  postgres:
    container_name: 'postgresql_container'
    image: postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - '5450:5432'
    volumes:
      - ./db/:/var/lib/postgresql/data
